<?php

/**
 * CityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('City');
    }

    public function getByAlphabet( $countryCode = NULL, $isVacation = 0 ) {

      $q = $this->createQuery('c')
        ->orderBy('c.name ASC');

      if ( $countryCode ) $q->where('c.Country.code = ?', strtoupper ($countryCode) );
      if ( $isVacation ) $q->where('c.isVacation = ?', $isVacation );
  
      return $q->execute();
    }

    public function getAssocByAlphabet( $countryCode = NULL, $isVacation = 0 ) {
      //$Cities = Doctrine_Core::getTable('City')->getByAlphabet();
      $data = array();
      foreach ($this->getByAlphabet( $countryCode, $isVacation ) as $City) {
        $data[ mb_substr($City->name, 0, 1) ][] = $City;
      }
      return $data;
    }

    // Returns only cities with weather data for current date
    public function getAssocByAlphabetClean( $countryCode = NULL, $isVacation = 0, $date = NULL ) {
      if ( !$date ) return false;

      $data = array();
      foreach ($this->getByAlphabet( $countryCode, $isVacation ) as $City) {
        if ( !$City->dayWeather($date) ) continue;
        $data[ mb_substr($City->name, 0, 1) ][] = $City;
      }
      return $data;
    }
}
