<?php

/**
 * City
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class City extends BaseCity
{

  // Return eng city name
  public function getEngName() {
    return $this->_get('name');
  }

  // Default name language override
  public function getName() {
    return $this->_get('geName');
  }

    // Returns weather by date
    public function dayWeather( $date = NULL ) {

      if ( !$date ) {
        $date = date ( 'Y-m-d', time() );
      }

      $q = Doctrine_Query::create()
        ->from ('DailyWeather w')
        ->where ( 'w.city_id = ?', $this->id)
        ->andWhere ( 'w.date = ?', $date)
        ->limit(1);
      //echo $q->getSqlQuery();
      //reset(..) here
      $dayWeather = $q->execute();
      if (!$dayWeather->count()) return false;
      //echo count($dayWether);
      return $dayWeather[0];

    }

    // Returns 7 days DailyWeather objects begining with given date
    public function weekWeather( $firstDayDate = NULL ) {

      if ( !$firstDayDate ) {
        $firstDayDate = date ( 'Y-m-d', time() );
      }

      $q = Doctrine_Query::create()
        ->from ('DailyWeather w')
        ->where ( 'w.city_id = ?', $this->id)
        ->andWhere ( 'w.date >= ?', $firstDayDate)
        ->limit (7);

      // Good case but returns city as too
      $qq = Doctrine_Query::create()
        ->from ('DailyWeather w')
        ->leftJoin ('w.City c')
        ->where ( 'w.city_id = ?', $this->id)
        ->andWhere ( 'w.date >= ?', $firstDayDate)
        ->limit (7);

      // Good case but returns city as root element
      $qqq = Doctrine_Query::create()
        ->from ('City c')
        ->leftJoin ('c.DailyWeather w')
        ->where ( 'w.city_id = ?', $this->id)
        ->andWhere ( 'w.date >= ?', $firstDayDate)
        ->limit (7);

      return $q->execute();

    }
}
