<?php

/**
 * DailyWeatherTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DailyWeatherTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DailyWeatherTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DailyWeather');
    }

}
