<?php

/**
 * DayWeatherTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DayWeatherTable extends DetailedWeatherTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object DayWeatherTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DayWeather');
    }
}