<?php

/**
 * DetailedWeatherTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DetailedWeatherTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DetailedWeatherTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DetailedWeather');
    }
}