<?php

/**
 * EngGeDictTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EngGeDictTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EngGeDictTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EngGeDict');
    }
}