<?php

/**
 * EveningWeatherTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EveningWeatherTable extends DetailedWeatherTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object EveningWeatherTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EveningWeather');
    }
}