<?php

/**
 * MorningWeatherTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MorningWeatherTable extends DetailedWeatherTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object MorningWeatherTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MorningWeather');
    }
}