<?php

/**
 * NightWeatherTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NightWeatherTable extends DetailedWeatherTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object NightWeatherTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NightWeather');
    }
}